//! trust — surface the CA cert + the env vars every coding agent needs.
//!
//! Trusting ccft means pointing an agent's outbound HTTP at ccft (so the
//! flytrap can tap the stream) *and* making the agent trust ccft's CA (so TLS
//! interception doesn't trip a certificate error). Rather than special-case
//! each agent's config file, `ccft trust --apply` writes one env block into
//! ccft's dot directory (`~/.cc-flytrap/ccft.env`) and sources it from every
//! shell RC it finds in `$HOME`. Any agent launched from a shell — Claude
//! Code, pi, opencode, aider, etc. — then inherits the same effective outcome:
//! `HTTPS_PROXY`/`HTTP_PROXY` → ccft, `NODE_EXTRA_CA_CERTS` → ccft's CA.
//!
//! This used to be auto-applied to ~/.claude.json by the bash installer, which
//! caused real damage when the flytrap went down (claude → connection refused).
//! Default here is print + you decide. `--apply` flag opts in to mutation with
//! backups; `--revoke` undoes it.

use crate::config::{paths, Config};
use crate::flytrap;
use serde_json::Value;
use std::fs;
use std::path::PathBuf;

/// Shell RC files we source the trust env from. The "always" files (`.zshenv`
/// for zsh, `.profile` for login shells) cover non-interactive launches; the
/// interactive ones (`.zshrc`, `.bashrc`, …) cover normal terminals. We touch
/// every one that exists so trust survives whichever shell the user picks.
const SHELL_RCS: &[&str] = &[
    ".zshenv",
    ".zprofile",
    ".zshrc",
    ".bashrc",
    ".bash_profile",
    ".profile",
    ".kshrc",
    ".shrc",
];

pub fn ensure_ca() -> Result<(), Box<dyn std::error::Error>> {
    if paths::ca_pem().exists() && paths::ca_key().exists() {
        return Ok(());
    }
    // Run the async generator on a small ad-hoc runtime.
    let rt = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()?;
    rt.block_on(async {
        flytrap::load_or_generate_ca().await?;
        Ok::<_, Box<dyn std::error::Error>>(())
    })?;
    Ok(())
}

pub fn print_instructions() {
    print_instructions_with(false);
}

fn cfg_for(dev: bool) -> Config {
    if dev {
        let mut c = Config::load_dev();
        if c.port == Config::default().port {
            c.port = 7179;
        }
        c
    } else {
        Config::load()
    }
}

pub fn print_instructions_with(dev: bool) {
    let cfg = cfg_for(dev);
    let ca = paths::ca_pem();
    let env = paths::env_file();
    println!("To route any coding agent through ccft (Claude Code, pi, opencode, …):");
    println!();
    println!("  export HTTPS_PROXY=http://{}:{}", cfg.host, cfg.port);
    println!("  export HTTP_PROXY=http://{}:{}", cfg.host, cfg.port);
    println!("  export NODE_EXTRA_CA_CERTS={}", ca.display());
    println!();
    println!("Or persist for every shell-launched agent: `ccft trust --apply`");
    println!("  writes the above into {} (a backup is kept),", env.display());
    println!("  sources it from every shell RC found in {} (idempotent), and", paths::home().display());
    println!("  keeps the existing ~/.claude.json env block for Claude Code.");
    println!("To remove: `ccft trust --revoke`");
    println!();
    println!("Local plain-HTTP OpenAI servers (Ollama / LM Studio / llama.cpp / ds4)");
    println!("need no CA — ccft forwards the absolute-form request and taps the SSE");
    println!("stream for the ledger. Remote HTTPS providers ride the CONNECT tunnel and");
    println!("use NODE_EXTRA_CA_CERTS above.");
    println!();
    println!("Verify Claude:");
    println!("  HTTPS_PROXY=http://{host}:{port} \\", host = cfg.host, port = cfg.port);
    println!("  NODE_EXTRA_CA_CERTS={} \\", ca.display());
    println!("  claude -p \"hi\"");
}

/// Write the trust env block into ccft's dot directory. Plain `export` lines
/// so it works when sourced by zsh/bash/ksh/sh.
fn write_env_file(cfg: &Config) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let env = paths::env_file();
    if let Some(dir) = env.parent() {
        fs::create_dir_all(dir)?;
    }
    let proxy = format!("http://{}:{}", cfg.host, cfg.port);
    let body = format!(
        "# ccft flytrap trust — generated by `ccft trust --apply`\n\
         # Remove with `ccft trust --revoke`.\n\
         export HTTPS_PROXY={proxy}\n\
         export HTTP_PROXY={proxy}\n\
         export NODE_EXTRA_CA_CERTS={ca}\n",
        proxy = proxy,
        ca = paths::ca_pem().to_string_lossy(),
    );
    fs::write(&env, body)?;
    println!("✓ wrote {}", env.display());
    Ok(env)
}

/// The one-line sourcing snippet, guarded by file existence so re-sourcing is
/// harmless if a RC is read twice.
fn sourcing_line(env: &PathBuf) -> String {
    format!(
        "# ccft flytrap trust (`ccft trust --apply`); remove with `ccft trust --revoke`\n\
         [ -f \"{}\" ] && . \"{}\"\n",
        env.to_string_lossy(),
        env.to_string_lossy()
    )
}

fn shell_rc_files() -> Vec<PathBuf> {
    let home = paths::home();
    SHELL_RCS
        .iter()
        .filter_map(|name| {
            let p = home.join(name);
            p.is_file().then(|| p)
        })
        .collect()
}

fn source_into_rcs(env: &PathBuf) -> Result<(), Box<dyn std::error::Error>> {
    let line = sourcing_line(env);
    for rc in shell_rc_files() {
        let raw = fs::read_to_string(&rc)?;
        if raw.contains("ccft.env") {
            // Already sourced; leave it alone.
            continue;
        }
        let out = format!("{}\n\n{}", raw.trim_end(), line);
        fs::write(&rc, out)?;
        println!("✓ sourced ccft trust into {}", rc.display());
    }
    Ok(())
}

fn unsource_from_rcs() -> Result<(), Box<dyn std::error::Error>> {
    for rc in shell_rc_files() {
        let raw = fs::read_to_string(&rc)?;
        if !raw.contains("ccft.env") {
            continue;
        }
        // Drop every line mentioning our marker comment or the env file.
        let kept: Vec<&str> = raw
            .lines()
            .filter(|l| !l.contains("ccft flytrap trust") && !l.contains("ccft.env"))
            .collect();
        // Trim the blank line the append left behind.
        let out = kept.join("\n").trim_end().to_string() + "\n";
        fs::write(&rc, out)?;
        println!("✓ removed ccft trust from {}", rc.display());
    }
    Ok(())
}

pub fn apply() -> Result<(), Box<dyn std::error::Error>> {
    apply_with(false)
}

pub fn apply_with(dev: bool) -> Result<(), Box<dyn std::error::Error>> {
    ensure_ca()?;
    let cfg = cfg_for(dev);
    let label = if dev { "dev" } else { "production" };

    // 1. The universal env block, sourced from shell RCs.
    let env = write_env_file(&cfg)?;
    source_into_rcs(&env)?;

    // 2. Keep the Claude Code ~/.claude.json env block (pre-existing behavior,
    //    so `claude` trusts ccft even when launched outside a sourced shell).
    let claude_json = paths::home().join(".claude.json");
    let mut data: Value = if claude_json.exists() {
        let raw = fs::read_to_string(&claude_json)?;
        // Backup before any mutation.
        let bak = claude_json.with_extension("json.bak");
        fs::write(&bak, &raw)?;
        println!("✓ backup → {}", bak.display());
        serde_json::from_str(&raw).unwrap_or_else(|_| serde_json::json!({}))
    } else {
        serde_json::json!({})
    };

    let env = data
        .as_object_mut()
        .ok_or("~/.claude.json root is not an object")?
        .entry("env")
        .or_insert_with(|| serde_json::json!({}));
    let env_obj = env.as_object_mut().ok_or("env is not an object")?;
    env_obj.insert(
        "HTTPS_PROXY".into(),
        Value::String(format!("http://{}:{}", cfg.host, cfg.port)),
    );
    env_obj.insert(
        "NODE_EXTRA_CA_CERTS".into(),
        Value::String(paths::ca_pem().to_string_lossy().to_string()),
    );

    fs::write(&claude_json, serde_json::to_string_pretty(&data)? + "\n")?;
    println!("✓ wrote env block to {}", claude_json.display());

    println!();
    println!("Trust applied for the {label} flytrap on :{port}.", label = label, port = cfg.port);
    println!("Restart any running agents (pi, claude, opencode) so they");
    println!("re-pick-up the shell env / config. New terminals inherit it automatically.");
    Ok(())
}

pub fn revoke() -> Result<(), Box<dyn std::error::Error>> {
    revoke_with(false)
}

pub fn revoke_with(_dev: bool) -> Result<(), Box<dyn std::error::Error>> {
    // 1. Stop sourcing the env block from every shell RC.
    unsource_from_rcs()?;

    // 2. Remove the env block file itself so no stale proxy/CA lingers.
    let env = paths::env_file();
    if env.exists() {
        fs::remove_file(&env)?;
        println!("✓ removed {}", env.display());
    }

    // 3. Undo the Claude Code ~/.claude.json env block.
    let claude_json = paths::home().join(".claude.json");
    if claude_json.exists() {
        let raw = fs::read_to_string(&claude_json)?;
        let bak = claude_json.with_extension("json.bak");
        fs::write(&bak, &raw)?;
        println!("✓ backup → {}", bak.display());

        let mut data: Value = serde_json::from_str(&raw)?;
        if let Some(obj) = data.as_object_mut() {
            if let Some(env) = obj.get_mut("env").and_then(Value::as_object_mut) {
                env.remove("HTTPS_PROXY");
                env.remove("HTTP_PROXY");
                env.remove("NODE_EXTRA_CA_CERTS");
            }
        }
        fs::write(&claude_json, serde_json::to_string_pretty(&data)? + "\n")?;
        println!("✓ removed flytrap env from {}", claude_json.display());
    }

    println!();
    println!("Trust revoked. Restart running agents; new shells no longer route through ccft.");
    Ok(())
}

pub fn print_ca() -> Result<(), Box<dyn std::error::Error>> {
    ensure_ca()?;
    let pem = fs::read_to_string(paths::ca_pem())?;
    print!("{}", pem);
    Ok(())
}
